<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Implements hook_menu().
 */
function my_popup_menu() {
  $items = array();

  $items['my/page'] = array(
    'page callback' => 'my_popup_page',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['my/%ctools_js'] = array(
    'page callback' => 'my_popup_callback',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

//  $items['mymodule/form'] = array(
//    'page callback' => 'drupal_get_form',
//    'page arguments' => array('my_popup_form'),
//    'access arguments' => array('administer mymodule'),
//    'modal' => TRUE, // This line is where the magic happens.
//  );

  return $items;
}

/**
 * Helper function to make a link.
 */
function _my_popup_make_link($link_text = '') {
  // Set a default value if no text in supplied.
  if (empty($link_text)) {
    $link_text = 'Magical Modal';
  }
//  print l(t('Click me! I`m a modal'), 'mymodule/form');
  return '<div id="magical-modal-link">' . l($link_text, 'my/nojs', array('attributes' => array('class' => 'ctools-use-modal'))) . '</div>';
}

/**
 * An example page.
 */
function my_popup_page() {
  // Load the modal library and add the modal javascript.
  ctools_include('modal');
  ctools_modal_add_js();
  return _my_popup_make_link('Magical modal');
}

/**
 * Ajax menu callback.
 */
function my_popup_callback($ajax) {

  $popup_content = '<img src="http://localhost/des/sites/default/files/styles/thumbnail/public/914SvaQsGZL._UX522_.jpg">';

  if ($ajax) {
    ctools_include('ajax');
    ctools_include('modal');

    $output = array();
    $output[] = ctools_modal_command_display(t('My first popup'), $popup_content);
    print ajax_render($output);
    drupal_exit();
  }
  else {
    return $popup_content;
  }
}

/**
 * Drupal form to be put in a modal.
 */
function my_popup_form($form, $form_state) {
  $form = array();

  $form['new_link_text'] = array(
    '#type' => 'textfield',
    '#title' => t('Link text'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}

/**
 * 
 * @param type $variables
 */
function my_popup_preprocess_page(&$variables) {

  if ($variables['is_front']) {
//    dpm("home page");
    drupal_add_js(drupal_get_path('module', 'my_popup') . '/js/myscript.js');
  }
  else {
//    dpm("non home page");
//    drupal_add_js(drupal_get_path('module', 'my_popup') . '/js/myscript.js');
  }
}
/**
 * Implements hook_preprocess_html()
 */
function my_popup_preprocess_html() {
  drupal_add_library('system', 'drupal.ajax');
}
