<?php

/**
 * Implements fook_menu
 */
function demo_menu() {
  $items ['demo/show-entity'] = array(
    'title' => 'Demo Entity Display',
    'page callback' => 'random_show',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_entity_info().
 */
function demo_entity_info() {

  $info = array();

  $info['project'] = array(
    'label' => t('Project'),
    'base table' => 'demo_projects',
    'entity keys' => array(
      'id' => 'id',
      'label' => 'name',
    ),
    'entity class' => 'Entity',
    'controller class' => 'ProjectEntityController',
    'module' => 'demo',
  );

  return $info;
}

/**
 * Extending the EntityAPIController for the Project entity.
 */
class ProjectEntityController extends EntityAPIController {

  public function buildContent($entity, $view_mode = 'full', $langcode = NULL, $content = array()) {

    $build = parent::buildContent($entity, $view_mode, $langcode, $content);

    $build['description'] = array(
      '#type' => 'markup',
      '#markup' => check_plain($entity->description),
      '#prefix' => '<div class="project-description">',
      '#suffix' => '</div>',
    );
    $build['deadline'] = array(
      '#type' => 'markup',
      '#markup' => date('d F, Y', check_plain($entity->deadline)),
      '#prefix' => '<p>Deadline: ',
      '#suffix' => '</p>',
    );

    return $build;
  }

}

function random_show() {
  // $projects = entity_load('project', array(1, 2, 3));
  // dpm($projects);
//  //if (!isset($projects[3])) {
//    $entity = entity_create('project', array('id' => 3));
//    $entity->name = t('Spring House');
//    $entity->description = t('Some more lipsum.');
//    $entity->save();
//  //}
//  return 'Some string';
  
  $projects = entity_load('project', array(1, 2, 3));

  $list = entity_view('project', $projects);

  $output = array();

  foreach ($list['project'] as $project) {
    $output[] = drupal_render($project);
  }

  return implode($output);
}
